// <auto-generated />
using FacturaSii.src.FacturaComponent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FacturaSii.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250501214711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FacturaSii.src.Domain.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoRespuesta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Folio")
                        .HasColumnType("integer");

                    b.Property<string>("RutEmisor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutReceptor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("XmlGenerado")
                        .HasColumnType("xml");

                    b.HasKey("Id");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("FacturaSii.src.Domain.Entities.Factura", b =>
                {
                    b.OwnsMany("FacturaSii.src.Domain.ValueObjects.Item", "Items", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Cantidad")
                                .HasColumnType("integer");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("FacturaId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("PrecioUnitario")
                                .HasColumnType("numeric");

                            b1.HasKey("Id");

                            b1.HasIndex("FacturaId");

                            b1.ToTable("Item");

                            b1.WithOwner()
                                .HasForeignKey("FacturaId");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
